# 服务器配置
server.port=8080
server.servlet.context-path=/

# 数据库配置
spring.datasource.url=jdbc:mysql://localhost:3306/umbrellazg?useSSL=false&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=zhangge1121
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# JPA配置
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 日志配置
logging.level.root=DEBUG
logging.level.com.website.backend=DEBUG

# JWT配置
app.jwtSecret=YOUR_JWT_SECRET_KEY_HERE
app.jwtExpirationMs=86400000

# Redis 配置（本地连接）
spring.data.redis.host=localhost  # 使用 localhost 而非具体 IP
spring.data.redis.port=6379
spring.data.redis.password=1
spring.data.redis.database=0

# 游客登录信息过期时间(6小时)
app.guest.expirationMs=21600000